# Generated by Django 4.1.5 on 2023-06-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=25, verbose_name='Ник')),
                ('gender', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], default='m', max_length=1, verbose_name='Пол')),
                ('avatar', models.ImageField(default='theme/images/avatars/default.jpg', upload_to='theme/images/avatars', verbose_name='Аватар')),
                ('bdate', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации')),
                ('balance', models.IntegerField(default=0, verbose_name='Цена')),
                ('ismoderator', models.BooleanField(default=False, verbose_name='Является ли модератером')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение почты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
    ]
