# Generated by Django 4.1.5 on 2023-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='images/avatars')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('charapters_readed', models.IntegerField(default=0)),
                ('comics_readed', models.IntegerField(default=0)),
                ('bookmarks_favorites', models.ManyToManyField(blank=True, related_name='bookmarks_favorites', to='catalog.comic')),
                ('bookmarks_read', models.ManyToManyField(blank=True, related_name='bookmarks_read', to='catalog.comic')),
                ('bookmarks_readed', models.ManyToManyField(blank=True, related_name='bookmarks_readed', to='catalog.comic')),
                ('bookmarks_trash', models.ManyToManyField(blank=True, related_name='bookmarks_trash', to='catalog.comic')),
            ],
        ),
    ]
