# Generated by Django 4.1.5 on 2023-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
