# Generated by Django 4.1.5 on 2023-06-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='expirence',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='expirence_unitl_next_level',
            new_name='experience_unitl_next_level',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='expirence',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='expirence_unitl_next_level',
            new_name='experience_unitl_next_level',
        ),
    ]
