# Generated by Django 4.1.5 on 2023-06-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_expirence_pin_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isNickname',
            field=models.BooleanField(default=False, verbose_name='Звать ли по прозвищу'),
        ),
    ]
