# Generated by Django 4.1.5 on 2023-05-21 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_userinfo_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserInfomation',
        ),
    ]
