# Generated by Django 4.1.5 on 2023-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='theme/static/images/avatars/default.jpg', upload_to='theme/static/images/avatars', verbose_name='Аватар'),
        ),
    ]
