# Generated by Django 4.1.5 on 2023-06-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код подтверждения почты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='users.profile', verbose_name='Подписки'),
        ),
    ]
