import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { api } from "~/utils/api";

export default function SignIn() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const signin = api.useContext()

  async function submit() {
    signin.auth.signin.fetch({ email: email, password: password }).then( (data) => {
      console.log(data.token)
      window.localStorage.setItem("token", data.token || "")
    } )
  }

  return (
    <>
      <Head>
        <title>Onomics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-zinc-900 w-screen h-screen flex justify-center items-center">
        <div className="w-[1200px] h-[600px] bg-[#1b1b1c] rounded-lg">
          <div className="w-full mx-6 mt-4">
            <h1 className="text-gray-100 text-xl">Sign In</h1>
          </div>
          <div className="w-full px-6 mt-2 text-gray-100">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus nemo ratione inventore earum consequatur magnam praesentium, quae voluptas maxime obcaecati itaque quo molestiae ipsum tempora minus dicta, harum quaerat nesciunt.</p>
          </div>
          <div className="w-full flex flex-col justify-center items-center mt-4">
            {/* <Link href="/auth/signin" className="bg-[#2b2b2c] text-gray-100 px-4 py-2 rounded-md hover:bg-[#4b4b4c] mx-2">Sign In</Link>
            <Link href="/auth/signup" className="bg-[#2b2b2c] text-gray-100 px-4 py-2 rounded-md hover:bg-[#4b4b4c] mx-2">Sign Up</Link> */}
            <input className="bg-zinc-700 rounded-md outline-none text-gray-100 px-4 py-2 my-1" type="email" onChange={ ({ target }) => setEmail(target.value) } />
            <input className="bg-zinc-700 rounded-md outline-none text-gray-100 px-4 py-2 my-1" type="password" onChange={ ({ target }) => setPassword(target.value) } />
            <input className="bg-zinc-700 rounded-md outline-none text-gray-100 px-4 py-2 my-1" value="Sign in" type="button" onClick={ (e) => {
                submit()
            } } />
          </div>
        </div>
      </main>
    </>
  );
}
