import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { number } from "zod";
import { api } from "~/utils/api";
import { IUser } from "./api/interfaces";
// import {logout, isAuth } from "./api/user"

export default function Home() {
  const [user, setUser] = useState({} as IUser) 
  const context = api.useContext()

  async function getUserInfo() {
    context.users.getMyProfile.fetch({token: window.localStorage.getItem("token") || ""}).then( (data) => {
      console.log(data)
      setUser(data)
    } )
  }

  return (
    <>
      <Head>
        <title>Onomics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-zinc-900 w-screen h-screen flex justify-center items-center">
        <div className="w-[1200px] h-[600px] bg-[#1b1b1c] rounded-lg">
          <div className="w-full mx-6 mt-4">
            <h1 className="text-gray-100 text-xl">HomePage</h1>
          </div>
          <div className="w-full px-6 mt-2 text-gray-100">
          <p className="mx-4">{user?.username}</p>
          {/* <p className="mx-4">{isAuth() ? "True" : "False"}</p> */}
          <p className="mx-4">{user?.username}</p>
          <p className="mx-4">{user?.username}</p>
          </div>
          <div className="w-full flex flex-row justify-center items-center mt-4">
          <button className="bg-[#2b2b2c] text-gray-100 px-4 py-2 rounded-md hover:bg-[#4b4b4c] mx-2" onClick={ (e) => {getUserInfo()} }>User info</button>
          {/* {isAuth() && <button className="bg-[#2b2b2c] text-gray-100 px-4 py-2 rounded-md hover:bg-[#4b4b4c] mx-2" onClick={ (e) => {logout()} }>Logout</button>} */}
            <Link href="auth/signin" className="bg-[#2b2b2c] text-gray-100 px-4 py-2 rounded-md hover:bg-[#4b4b4c] mx-2">Sign In</Link>
            <Link href="auth/signup" className="bg-[#2b2b2c] text-gray-100 px-4 py-2 rounded-md hover:bg-[#4b4b4c] mx-2">Sign Up</Link>
          </div>
        </div>
      </main>
    </>
  );
}
