import React, { PropsWithChildren, ReactNode } from "react";
import Navbar from "~/Navbar/Navbar";
import Footer from "~/Footer/Footer";
import Head from "next/head";
 
export default function Layout({ children } : PropsWithChildren) : JSX.Element {
  return (
    <>
      <Head>
        <title>Onomics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="h-6 mt-[30px] hidden sm:block"><br/></div>
        <div className="w-full">
            <main className='w-auto flex-grow h-full my-2 box-border pb-24 overflow-x-hidden'>{children}</main>
        </div>
      <Footer />
    </>
  )
}