# Generated by Django 4.1.5 on 2023-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(upload_to='images/blocks', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='charapter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='catalog.comment', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='catalog.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(upload_to='static/images/covers', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='catalog.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
