# Generated by Django 4.1.5 on 2023-06-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_block_image_alter_comic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_id',
        ),
        migrations.AddField(
            model_name='block',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='bl_comments', to='catalog.comment', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='charapter',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='ch_comments', to='catalog.comment', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='comic',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('Complete', 'Вышел'), ('Ongoing', 'Выходит'), ('Anonce', 'Анонс')], default='Anonce', max_length=12, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='comic',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='Ответ на'),
        ),
    ]
