# Generated by Django 4.1.5 on 2023-06-15 16:10

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_comic_author_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='theme/images/blocks', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='theme/static/images/covers', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_id',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.comment', verbose_name='Ответ на'),
        ),
    ]
