# Generated by Django 4.1.5 on 2023-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_block_image_alter_comic_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(upload_to='theme/images/blocks', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(upload_to='theme/static/images/covers', verbose_name='Обложка'),
        ),
    ]
