# Generated by Django 4.1.5 on 2023-06-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_block_image_alter_comic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(upload_to='covers/<django.db.models.fields.AutoField>', verbose_name='Обложка'),
        ),
    ]
