# Generated by Django 4.1.5 on 2023-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_comic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(upload_to='theme/static/covers/', verbose_name='Обложка'),
        ),
    ]
