# Generated by Django 4.1.5 on 2023-06-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_comic_author_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_id',
            new_name='reply',
        ),
    ]
