# Generated by Django 4.1.5 on 2023-06-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_charapter_moderation_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charapter',
            new_name='Chapter',
        ),
    ]
